[functions.request-admin-code]
verify_jwt = false

[functions.verify-admin-code]
verify_jwt = false

[functions.check-admin-access]
verify_jwt = false

[functions.create-product]
verify_jwt = false

[functions.manage-hero-slide]
verify_jwt = false

[functions.manage-product]
verify_jwt = false

[functions.manage-sales]
verify_jwt = false

[functions.manage-category-image]
verify_jwt = false

[functions.manage-finances]
verify_jwt = false

[functions.run-financial-reports]
verify_jwt = false
